'use strict'

module.exports = function (shariff) {
  var url = encodeURIComponent(shariff.getURL())
  return {
    popup: true,
    shareText: {
      bg: 'cподеляне',
      cs: 'sdílet',
      da: 'del',
      de: 'teilen',
      en: 'share',
      es: 'compartir',
      fi: 'Jaa',
      fr: 'partager',
      hr: 'podijelite',
      hu: 'megosztás',
      it: 'condividi',
      ja: '共有',
      ko: '공유하기',
      nl: 'delen',
      no: 'del',
      pl: 'udostępnij',
      pt: 'compartilhar',
      ro: 'partajează',
      ru: 'поделиться',
      sk: 'zdieľať',
      sl: 'deli',
      sr: 'podeli',
      sv: 'dela',
      tr: 'paylaş',
      zh: '分享',
    },
    name: 'mix',
    faPrefix: 'fab fa-brands',
    faName: 'fa-mix',
    title: {
      bg: 'Сподели в Mix',
      cs: 'Sdílet na Mixu',
      da: 'Del på Mix',
      de: 'Auf Mix teilen',
      en: 'Share on Mix',
      es: 'Compartir en Mix',
      fi: 'Jaa Mixissä',
      fr: 'Partager sur Mix',
      hr: 'Podijeli na Mixu',
      hu: 'Megosztás a Mixen',
      it: 'Condividi su Mix',
      ja: 'Mixでシェアする',
      ko: 'Mix에 공유하기',
      nl: 'Delen op Mix',
      no: 'Del på Mix',
      pl: 'Udostępnij na Mix',
      pt: 'Compartilhar no Mix',
      ro: 'Partajează pe Mix',
      ru: 'Поделиться на Mix',
      sk: 'Zdieľať na Mix',
      sl: 'Deli na Mixu',
      sr: 'Podeli na Mixu',
      sv: 'Dela på Mix',
      tr: "Mix'te paylaş",
      zh: '在 Mix 上分享',
    },
    shareUrl:
      'https://mix.com/add?url=' +
      url +
      shariff.getReferrerTrack(),
  }
}
