language: node_js

sudo: false

node_js:
  - "node"

addons:
  apt:
    packages:
      - p7zip-full

env:
  global:
    - BASE_NAME=shariff-plus-$TRAVIS_TAG

script:
  - npm run test

before_deploy:
  - npm run build
  - npm run build_zip

deploy:
  - provider: releases
    api_key:
      secure: "H6X2U+rjwgA9ieP48oeCEGMGmXDq//GhFQctJYY8cRGSmDMfG2roOP0pPY8aK0+y5JDaQg/AI8YNBNyaqiAwiVyYiGdnnmlcyCjXE6cMxObf+1MU98ncCuZUfkK9poq7VzrjYlnT0u1pCMBzgCNUxQNxn+QXZI+RbGHxvQzsnlHAU5SjQWLqi/jB4trCjeyeYbEhI+cRoE86IqzEmVBCUGnH+7XB0P6qUOVYKh2HquUGiRFN7OZyj3o03xzaBhrBnucn5hc8QhnJ2aR+GBmFw09NMxfARGkiU81TcnsluurFi0jrRYxpQbttIHHPJ0Jn+ExzzbqeUzZA6gM8tQU3dJLUU7Z9Y6RmT9z5iQBG5bq6BTMv6r3zfata2pU7d3WDjstXVDfDrh5EC471U4Lh16wqdAgNhbYTn+fp3uuiRyDNbF7TPbwmStGYo5wMevFOYsr+c8V+hc2qdyJp44I/6abAp/Ytbo4n26hKJZitWRzklVMbpHche2fRAHFN6MdhOgjFcJGJiO4LBEmbR8TXTPia5GIMO+Ejk6m4oB/7hCYA6+R2hPcxSnz1SpQVBYi4WA2Y7diH7ahmraY/ccPhd5V3JjrG03LQFBuu+F+FyOuIW2w6PaKWjKg7vxwcJcGomhm1hs5hHb2yx9r9/YB8qevpM4NtcxlZhcPjHLsSmTw="
    file:
      - $BASE_NAME.zip
      - $BASE_NAME.tar.gz
    skip_cleanup: true
    on:
      repo: richard67/shariff-plus
      tags: true
  - provider: npm
    email: richard.fath@t-online.de
    api_key:
      secure: "W036KiSfvzPegkQ+oyq4eE2nVUy7CmUO/5a8OYxF5J8yUo71FRaxF0R9zVKjzhDZXpCGmUSmF/AXaAKviyIhhY4ruAzthn7wUAHzfxBYKgf+VAZLQdSojR5VjPU4g8BbrwC4IGp9tTf49wyMGdpfJXjwchQWltWor1vDIqFw5gCFQVEx6Ryh5wT6sSPhkHQxsceaRE/SqDlroeT0SCtt6FrIS+/0Dbi6eK2Xk+Wr2JfrhjAC01iuG83O/UnlrDqSGeMwrGSgOsTJBHj0Uifsz9UeP3KLFa8rjZmnXikbbiH1cX4afrp9g8c+hRb0HxRZ1o98JI5tba/WTZ2zVFUVO4JCKQAPZSRrmWd9IrkE6Ee9qLg3BLJwF4Qu0uvF9OIo+/YWtJQ8pRJ5HBy/coEdsKMuHl6MyLWdQe/8+GrSQXK6+2iR5jGMZLuZf43f40eGCzPHWn+JPZ+iUMVsHto0Lzydbvka0rtSqYnj4oL/zmzb+Fb+VfsWE/dz57bWMr1lgdmWAC91/DGpkM6fnmsi3sko5S9niWVQnYUF5qd4aalURPu2tXAGbBY/JJYtfwxoZCopghG6Ea+gpYUa7ihByhoCRC3jq13btxbSNqSxov45cfm2zbuXvCX1Bp9Zz46JFXvvKE3kdlSP0IUYkYS1jBIKzEs3AP/J9fqAAzKI/6Q="
    skip_cleanup: true
    on:
      repo: richard67/shariff-plus
      tags: true
