language: node_js

sudo: false

node_js:
  - "node"

addons:
  apt:
    packages:
      - p7zip-full

env:
  global:
    - BASE_NAME=shariff-plus-$TRAVIS_TAG

script:
  - npm run test

before_deploy:
  - npm run build
  - npm run build_zip

deploy:
  - provider: releases
    api_key:
      secure: "H6X2U+rjwgA9ieP48oeCEGMGmXDq//GhFQctJYY8cRGSmDMfG2roOP0pPY8aK0+y5JDaQg/AI8YNBNyaqiAwiVyYiGdnnmlcyCjXE6cMxObf+1MU98ncCuZUfkK9poq7VzrjYlnT0u1pCMBzgCNUxQNxn+QXZI+RbGHxvQzsnlHAU5SjQWLqi/jB4trCjeyeYbEhI+cRoE86IqzEmVBCUGnH+7XB0P6qUOVYKh2HquUGiRFN7OZyj3o03xzaBhrBnucn5hc8QhnJ2aR+GBmFw09NMxfARGkiU81TcnsluurFi0jrRYxpQbttIHHPJ0Jn+ExzzbqeUzZA6gM8tQU3dJLUU7Z9Y6RmT9z5iQBG5bq6BTMv6r3zfata2pU7d3WDjstXVDfDrh5EC471U4Lh16wqdAgNhbYTn+fp3uuiRyDNbF7TPbwmStGYo5wMevFOYsr+c8V+hc2qdyJp44I/6abAp/Ytbo4n26hKJZitWRzklVMbpHche2fRAHFN6MdhOgjFcJGJiO4LBEmbR8TXTPia5GIMO+Ejk6m4oB/7hCYA6+R2hPcxSnz1SpQVBYi4WA2Y7diH7ahmraY/ccPhd5V3JjrG03LQFBuu+F+FyOuIW2w6PaKWjKg7vxwcJcGomhm1hs5hHb2yx9r9/YB8qevpM4NtcxlZhcPjHLsSmTw="
    file:
      - $BASE_NAME.zip
      - $BASE_NAME.tar.gz
    skip_cleanup: true
    on:
      repo: richard67/shariff-plus
      tags: true
  - provider: npm
    email: richard.fath@t-online.de
    api_key:
      secure: "FG3g1VGCI2iUEEJFWdKJqVtf48pQ7jOVCxUD/5UrEfZ8rRZgGVdqM7K0Yuy+RZyS9WtABVbYBV7sZgItdn30t9APDiBmjG6tx9SKyFFE6n3loaeyljB7AxG92H6JXUaexxRJahdt8U6xC+JJIXDSim9MMtrpepcQutlnvGZNKGyvdnHdiwfJlTwkPcTtGDU0zSa8BF3FHj/S0Chun3r3pNFOUD7EtUqDXKp3SfMxFSyE0I1qdeH/QkYt9tDebtVGIiAdqG1L12yNlTocSqO8I0joe4/fp0FnTexvwGtuPXvfTM0JoGSrFFnNZVlbZS9iDeGdBD7SGxQ4uh4RgzgOeOzXsqrSahso3iVHyinKrxpsxHz0Tv6xFCNDmj3nEYyR5f0D+MSo+9tCkxx6OXnP+bdj4L+fo5rqxoyng5XB38nKnGTaP0gGTaOWEjnHSrbSd/agh4qiD7rqQPxsjFz1WHnrXAFgfsp9L4ta6aWc7mT4YEHn91jKA5fqI8F9viB7SOovDB3vz44DNLdhXuzWK6TDs0bfMx0fLoN1edsJmQQ2hlx39hTtGmn7vTgmemcR48daCLllaLFqBAPjUd8Dq7/vBEIJBQr+wyop6jrf/Cva9vQ1Px6D5NcKN7LwZbqFnBiD6AsQDXpsvMZWehMI3h2/UYyEtqu524uM0Os1I70="
    skip_cleanup: true
    on:
      repo: richard67/shariff-plus
      tags: true
