language: node_js

sudo: false

node_js:
  - "node"

addons:
  apt:
    packages:
      - p7zip-full

env:
  global:
    - BASE_NAME=shariff-plus-$TRAVIS_TAG

cache:
  directories:
    - node_modules

script:
  - npm run test

before_deploy:
  - npm run build
  - npm run build_zip

deploy:
  - provider: releases
    api_key:
      secure: "H6X2U+rjwgA9ieP48oeCEGMGmXDq//GhFQctJYY8cRGSmDMfG2roOP0pPY8aK0+y5JDaQg/AI8YNBNyaqiAwiVyYiGdnnmlcyCjXE6cMxObf+1MU98ncCuZUfkK9poq7VzrjYlnT0u1pCMBzgCNUxQNxn+QXZI+RbGHxvQzsnlHAU5SjQWLqi/jB4trCjeyeYbEhI+cRoE86IqzEmVBCUGnH+7XB0P6qUOVYKh2HquUGiRFN7OZyj3o03xzaBhrBnucn5hc8QhnJ2aR+GBmFw09NMxfARGkiU81TcnsluurFi0jrRYxpQbttIHHPJ0Jn+ExzzbqeUzZA6gM8tQU3dJLUU7Z9Y6RmT9z5iQBG5bq6BTMv6r3zfata2pU7d3WDjstXVDfDrh5EC471U4Lh16wqdAgNhbYTn+fp3uuiRyDNbF7TPbwmStGYo5wMevFOYsr+c8V+hc2qdyJp44I/6abAp/Ytbo4n26hKJZitWRzklVMbpHche2fRAHFN6MdhOgjFcJGJiO4LBEmbR8TXTPia5GIMO+Ejk6m4oB/7hCYA6+R2hPcxSnz1SpQVBYi4WA2Y7diH7ahmraY/ccPhd5V3JjrG03LQFBuu+F+FyOuIW2w6PaKWjKg7vxwcJcGomhm1hs5hHb2yx9r9/YB8qevpM4NtcxlZhcPjHLsSmTw="
    file:
      - $BASE_NAME.zip
      - $BASE_NAME.tar.gz
    skip_cleanup: true
    on:
      repo: richard67/shariff-plus
      tags: true
  - provider: npm
    email: richard.fath@t-online.de
    api_key:
      secure: aJH9DD9gr7uGqo5RrPgJ72uAaCsRMiEqm262fEebJre3q8F9l9KhU4QWOEd7YtmO6qS/fJ9+rybDTEoUTbZg5heBXgK8+fqAvcoRZhdbDsHvzH6fG/1B9VkJTnwPC1A+6LgjAVbpi2W1a2/+bDIesbZ8wG7tKFHSDSK4KE+OZhjitQu4aXjFmXX52aiqw70w670AQgJLNq5AnyXy0OFmly3eNv29AYGBbkWo8q0ut/G6+9ELeRtsEFsJ8VcRRdJ1VqmcIQIuE6R6CYqqzALzKIJ4rNJhoQsuvApABnv0STW50X14jFxHcC9SoYlSQO6zLc7DcDl46bCrAsPE2acoiVav7mOE0g90D6ubdShHBkW9tOMX78jCXeajUIm4ZZ1KpoEpSAuQF0SwJOQcm3nvMmmViycpv5dBt1NtPkQVOdrydUJ6KTs5V7jMe3vShswTM/gVbgwJe2+DgUC47bQCuRBwpkeo00AxMvD+rE7QNJlF/X/bzaIjyQD7STW+KlSVWAywR/dFxMrGn+f+Q4146K9SF1YitpTqOPPrpGesy1JzZM3wLweyRH9BjqC51QPjYs9ZxAupAyTf7b7EspItdSdAPKVEHzQUbH85wJ4UZj7gZH7PPncMnmpcHvQiv9s0som9Okr1DkoDSn7HVFSwObvpWLox7YgSdeI5q3TH87M=
    skip_cleanup: true
    on:
      repo: richard67/shariff-plus
      tags: true
